import type { HubPageConfig } from '@/components/hub/HubComponents';

export const HUB_CONFIGS: Record<string, HubPageConfig> = {
    food: {
        type: 'food',
        slug: 'food',
        pageKey: 'food-stores',
        fallbackTitle: 'Island Flavors',
        heroSubtitle: '🍳 Fresh kitchens • 🍽️ Top restaurants • ☕ Cozy cafés',
        heroEmoji: '🍽️🍜☕',
        heroStats: { label: 'Places', emoji: '🌴' },
        categories: [
            { id: 'all', title: 'All', icon: '🍽️', desc: '', subtypes: [] },
            { id: 'kitchen', title: 'Kitchens', icon: '🍳', desc: 'Home-cooked & cloud kitchens', subtypes: ['kitchen', 'cloud_kitchen', 'home_cooking'] },
            { id: 'restaurant', title: 'Restaurants', icon: '🍽️', desc: 'Full-service dining', subtypes: ['restaurant', 'dining', 'fine_dining'] },
            { id: 'cafe', title: 'Cafés', icon: '☕', desc: 'Coffee, pastries & light bites', subtypes: ['cafe', 'coffee', 'bakery', 'pastry'] },
            { id: 'grill', title: 'Grills & Bars', icon: '🍺', desc: 'BBQ, grills & nightlife', subtypes: ['grill', 'bar', 'bbq', 'nightlife', 'pub'] },
        ],
        theme: {
            primary: 'orange',
            gradient: 'from-orange-500 to-red-500',
            lightBg: 'bg-orange-50 dark:bg-orange-900/20',
            lightText: 'text-orange-600 dark:text-orange-400',
            border: 'border-orange-100 dark:border-orange-900/30',
            ring: 'ring-orange-200 dark:ring-orange-800',
            accentBg: 'bg-orange-500',
        },
        storeCardVariant: 'food',
        ctaTitle: 'Own a Kitchen or Restaurant?',
        ctaSubtitle: "Join IslandHub's food court 🍴 and serve thousands of hungry customers across the Caribbean!",
        ctaEmoji: '🍳',
        searchPlaceholder: '🍽️ Search kitchens, restaurants, cafés...',
    },

    products: {
        type: 'products',
        slug: 'products',
        pageKey: 'product-stores',
        fallbackTitle: 'Island Marketplace',
        heroSubtitle: '🛍️ Local crafts • 🎨 Artisan goods • 🌿 Natural products',
        heroEmoji: '🛍️🎨🌿',
        heroStats: { label: 'Shops', emoji: '🌴' },
        categories: [
            { id: 'all', title: 'All', icon: '🛍️', desc: '', subtypes: [] },
            { id: 'shop', title: 'Shops', icon: '🏪', desc: 'General retail stores', subtypes: ['shop', 'retail', 'general'] },
            { id: 'specialty', title: 'Specialty', icon: '🎨', desc: 'Artisan & specialty goods', subtypes: ['specialty_food', 'artisan', 'craft', 'handmade'] },
            { id: 'fashion', title: 'Fashion', icon: '👗', desc: 'Clothing, shoes & accessories', subtypes: ['fashion', 'clothing', 'shoes', 'accessories'] },
            { id: 'health', title: 'Health', icon: '💊', desc: 'Health, wellness & beauty', subtypes: ['health_beauty', 'wellness', 'supplements'] },
        ],
        theme: {
            primary: 'emerald',
            gradient: 'from-emerald-500 to-teal-500',
            lightBg: 'bg-emerald-50 dark:bg-emerald-900/20',
            lightText: 'text-emerald-600 dark:text-emerald-400',
            border: 'border-emerald-100 dark:border-emerald-900/30',
            ring: 'ring-emerald-200 dark:ring-emerald-800',
            accentBg: 'bg-emerald-500',
        },
        storeCardVariant: 'product',
        ctaTitle: 'Sell Your Products',
        ctaSubtitle: 'Join IslandHub marketplace and reach thousands of customers across the Caribbean!',
        ctaEmoji: '🛍️',
        searchPlaceholder: '🛍️ Search products, shops, brands...',
    },

    services: {
        type: 'services',
        slug: 'services',
        pageKey: 'service-stores',
        fallbackTitle: 'Island Services',
        heroSubtitle: '🛠️ Professional • 🚗 Automotive • 💆 Health & Beauty',
        heroEmoji: '🛠️💼🚗',
        heroStats: { label: 'Providers', emoji: '🌴' },
        categories: [
            { id: 'all', title: 'All', icon: '🛠️', desc: '', subtypes: [] },
            { id: 'professional', title: 'Professional', icon: '💼', desc: 'Legal, consulting & business', subtypes: ['professional_services', 'legal', 'consulting', 'accounting'] },
            { id: 'automotive', title: 'Automotive', icon: '🚗', desc: 'Repair, detailing & maintenance', subtypes: ['automotive', 'car_repair', 'detailing'] },
            { id: 'health', title: 'Health & Beauty', icon: '💆', desc: 'Spa, wellness & personal care', subtypes: ['health_beauty', 'spa', 'wellness', 'salon'] },
            { id: 'marine', title: 'Marine', icon: '⚓', desc: 'Boat services & water activities', subtypes: ['marine', 'boat_service', 'diving'] },
            { id: 'events', title: 'Events', icon: '🎉', desc: 'Planning, catering & entertainment', subtypes: ['event_services', 'catering', 'entertainment', 'planning'] },
        ],
        theme: {
            primary: 'blue',
            gradient: 'from-blue-500 to-indigo-500',
            lightBg: 'bg-blue-50 dark:bg-blue-900/20',
            lightText: 'text-blue-600 dark:text-blue-400',
            border: 'border-blue-100 dark:border-blue-900/30',
            ring: 'ring-blue-200 dark:ring-blue-800',
            accentBg: 'bg-blue-500',
        },
        storeCardVariant: 'service',
        ctaTitle: 'Offer Your Services',
        ctaSubtitle: 'Join IslandHub and connect with customers looking for your expertise!',
        ctaEmoji: '🛠️',
        searchPlaceholder: '🛠️ Search services, providers...',
    },

    tours: {
        type: 'tours',
        slug: 'tours',
        pageKey: 'tour-hub',
        fallbackTitle: 'Island Adventures',
        heroSubtitle: '🥾 Land tours • 🌊 Sea adventures • 🧗 Extreme fun',
        heroEmoji: '🗺️🥾🌊',
        heroStats: { label: 'Tours', emoji: '🌴' },
        categories: [
            { id: 'all', title: 'All', icon: '🗺️', desc: '', subtypes: [] },
            { id: 'land', title: 'Land Tours', icon: '🥾', desc: 'Hiking, history & nature', subtypes: ['land', 'hiking', 'history', 'nature', 'culture'] },
            { id: 'sea', title: 'Sea & Water', icon: '🌊', desc: 'Snorkeling, sailing & fishing', subtypes: ['sea', 'snorkeling', 'sailing', 'fishing', 'diving'] },
            { id: 'adventure', title: 'Adventure', icon: '🧗', desc: 'Zip-lining, ATV & extreme', subtypes: ['adventure', 'zipline', 'atv', 'extreme'] },
            { id: 'charter', title: 'Charters', icon: '⛵', desc: 'Private boat & yacht charters', subtypes: ['charter', 'yacht', 'private_boat'] },
        ],
        theme: {
            primary: 'emerald',
            gradient: 'from-emerald-500 to-green-500',
            lightBg: 'bg-emerald-50 dark:bg-emerald-900/20',
            lightText: 'text-emerald-600 dark:text-emerald-400',
            border: 'border-emerald-100 dark:border-emerald-900/30',
            ring: 'ring-emerald-200 dark:ring-emerald-800',
            accentBg: 'bg-emerald-500',
        },
        storeCardVariant: 'tour',
        ctaTitle: 'Lead Tours & Adventures',
        ctaSubtitle: 'Share the beauty of the Caribbean with visitors from around the world!',
        ctaEmoji: '🗺️',
        searchPlaceholder: '🗺️ Search tours, adventures, charters...',
    },

    transport: {
        type: 'transport',
        slug: 'transport',
        pageKey: 'taxi-hub',
        fallbackTitle: 'Island Transport',
        heroSubtitle: '🚕 Ride hailing • 📦 Delivery • 🚤 Boat charters',
        heroEmoji: '🚕📦🚤',
        heroStats: { label: 'Drivers', emoji: '🌴' },
        categories: [
            { id: 'all', title: 'All', icon: '🚕', desc: '', subtypes: [] },
            { id: 'ride', title: 'Ride Hailing', icon: '🚕', desc: 'Quick rides across the island', subtypes: ['ride', 'taxi', 'ride_hail'] },
            { id: 'delivery', title: 'Delivery', icon: '📦', desc: 'Send packages and goods', subtypes: ['delivery', 'courier', 'package'] },
            { id: 'boat', title: 'Boat Charters', icon: '🚤', desc: 'Private boat and ferry services', subtypes: ['boat', 'ferry', 'charter', 'marine'] },
            { id: 'moving', title: 'Moving', icon: '🚚', desc: 'Relocation and heavy lifting', subtypes: ['moving', 'relocation', 'heavy'] },
        ],
        theme: {
            primary: 'sky',
            gradient: 'from-sky-500 to-blue-500',
            lightBg: 'bg-sky-50 dark:bg-sky-900/20',
            lightText: 'text-sky-600 dark:text-sky-400',
            border: 'border-sky-100 dark:border-sky-900/30',
            ring: 'ring-sky-200 dark:ring-sky-800',
            accentBg: 'bg-sky-500',
        },
        storeCardVariant: 'transport',
        ctaTitle: 'Become a Driver',
        ctaSubtitle: 'Join IslandHub transport network and earn on your schedule!',
        ctaEmoji: '🚕',
        searchPlaceholder: '🚕 Search rides, delivery, charters...',
    },

    rentals: {
        type: 'rentals',
        slug: 'rentals',
        pageKey: 'rental-hub',
        fallbackTitle: 'Island Stays',
        heroSubtitle: '🏠 Vacation homes • 🏖️ Beach villas • 🏢 Long-term rentals',
        heroEmoji: '🏠🏖️🏢',
        heroStats: { label: 'Properties', emoji: '🌴' },
        categories: [
            { id: 'all', title: 'All', icon: '🏠', desc: '', subtypes: [] },
            { id: 'stays', title: 'Vacation Stays', icon: '🏖️', desc: 'Short-term vacation rentals', subtypes: ['stays', 'vacation', 'airbnb', 'short_term'] },
            { id: 'longterm', title: 'Long-term', icon: '🏢', desc: 'Monthly & annual rentals', subtypes: ['long_term', 'monthly', 'annual', 'apartment'] },
            { id: 'equipment', title: 'Equipment', icon: '🔧', desc: 'Tools, gear & equipment', subtypes: ['equipment', 'tools', 'gear', 'rental_equipment'] },
        ],
        theme: {
            primary: 'amber',
            gradient: 'from-amber-500 to-orange-500',
            lightBg: 'bg-amber-50 dark:bg-amber-900/20',
            lightText: 'text-amber-600 dark:text-amber-400',
            border: 'border-amber-100 dark:border-amber-900/30',
            ring: 'ring-amber-200 dark:ring-amber-800',
            accentBg: 'bg-amber-500',
        },
        storeCardVariant: 'rental',
        ctaTitle: 'List Your Property',
        ctaSubtitle: 'Join IslandHub rentals and earn from your property!',
        ctaEmoji: '🏠',
        searchPlaceholder: '🏠 Search stays, rentals, equipment...',
    },

    campaigns: {
        type: 'campaigns',
        slug: 'campaigns',
        pageKey: 'campaigns',
        fallbackTitle: 'Island Causes',
        heroSubtitle: '❤️ Community fundraisers • 🌱 Environmental • 📚 Education',
        heroEmoji: '❤️🌱📚',
        heroStats: { label: 'Campaigns', emoji: '🌴' },
        categories: [
            { id: 'all', title: 'All', icon: '❤️', desc: '', subtypes: [] },
            { id: 'community', title: 'Community', icon: '🤝', desc: 'Local community projects', subtypes: ['community', 'local', 'neighborhood'] },
            { id: 'environment', title: 'Environment', icon: '🌱', desc: 'Eco & conservation', subtypes: ['environment', 'eco', 'conservation', 'green'] },
            { id: 'education', title: 'Education', icon: '📚', desc: 'Schools & learning', subtypes: ['education', 'school', 'learning', 'scholarship'] },
            { id: 'health', title: 'Health', icon: '🏥', desc: 'Medical & health causes', subtypes: ['health', 'medical', 'hospital', 'wellness'] },
        ],
        theme: {
            primary: 'rose',
            gradient: 'from-rose-500 to-pink-500',
            lightBg: 'bg-rose-50 dark:bg-rose-900/20',
            lightText: 'text-rose-600 dark:text-rose-400',
            border: 'border-rose-100 dark:border-rose-900/30',
            ring: 'ring-rose-200 dark:ring-rose-800',
            accentBg: 'bg-rose-500',
        },
        storeCardVariant: 'campaign',
        ctaTitle: 'Start a Campaign',
        ctaSubtitle: 'Raise funds for your cause and make a difference in the Caribbean!',
        ctaEmoji: '❤️',
        searchPlaceholder: '❤️ Search campaigns, causes...',
    },

    community: {
        type: 'community',
        slug: 'community',
        pageKey: 'community',
        fallbackTitle: 'Island Community',
        heroSubtitle: '🌴 Events • 📸 Stories • 🤝 Connect with locals',
        heroEmoji: '🌴📸🤝',
        heroStats: { label: 'Members', emoji: '🌴' },
        categories: [
            { id: 'all', title: 'All', icon: '🌴', desc: '', subtypes: [] },
            { id: 'events', title: 'Events', icon: '📅', desc: 'Upcoming local events', subtypes: ['event', 'meetup', 'gathering'] },
            { id: 'stories', title: 'Stories', icon: '📸', desc: 'Community stories & posts', subtypes: ['story', 'post', 'update'] },
            { id: 'groups', title: 'Groups', icon: '👥', desc: 'Interest-based groups', subtypes: ['group', 'club', 'association'] },
        ],
        theme: {
            primary: 'green',
            gradient: 'from-green-500 to-emerald-500',
            lightBg: 'bg-green-50 dark:bg-green-900/20',
            lightText: 'text-green-600 dark:text-green-400',
            border: 'border-green-100 dark:border-green-900/30',
            ring: 'ring-green-200 dark:ring-green-800',
            accentBg: 'bg-green-500',
        },
        storeCardVariant: 'community',
        ctaTitle: 'Join the Community',
        ctaSubtitle: 'Connect with locals, share stories, and be part of island life!',
        ctaEmoji: '🌴',
        searchPlaceholder: '🌴 Search community, events, groups...',
    },
};

export function getHubConfig(type: string): HubPageConfig | undefined {
    return HUB_CONFIGS[type];
}

export function getAllHubTypes(): string[] {
    return Object.keys(HUB_CONFIGS);
}
