import fs from 'fs';
import path from 'path';

export interface StorageProvider {
    uploadFile(file: Express.Multer.File): Promise<string>;
    deleteFile(filename: string): Promise<void>;
}

export class LocalStorageProvider implements StorageProvider {
    private uploadsDir: string;

    constructor(uploadsDir: string) {
        this.uploadsDir = uploadsDir;
        if (!fs.existsSync(this.uploadsDir)) {
            fs.mkdirSync(this.uploadsDir, { recursive: true });
        }
    }

    async uploadFile(file: Express.Multer.File): Promise<string> {
        // Filename is already generated by multer in our current setup
        // But we want to return the relative URL
        return `/uploads/${file.filename}`;
    }

    async deleteFile(filename: string): Promise<void> {
        const filePath = path.join(this.uploadsDir, filename);
        if (fs.existsSync(filePath)) {
            fs.unlinkSync(filePath);
        }
    }
}

// In the future, add S3StorageProvider, SupabaseStorageProvider, etc.
// export class S3StorageProvider implements StorageProvider { ... }
